UVM_HOME            :=  /home/synopsys/vcs-mx/O-2018.09-SP2/etc/uvm-1.1

PROJECT_PATH		:=	/home/ICer/ic_prjs/riscv/digital_data

PROJECT_DOC			:=	$(PROJECT_PATH)/doc
PROJECT_SCRIPT		:=	$(PROJECT_PATH)/script
PROJECT_SRC			:=	$(PROJECT_PATH)/src
PROJECT_VERIFACTION	:=	$(PROJECT_PATH)/verifaction/$(SIM_PATH)


PROJECT_SOCDIE		:= riscv
PROJECT_TOP         := harness
PROJECT_SOC			:= $(PROJECT_SRC)/$(PROJECT_SOCDIE)
PROJECT_SOCDOC		:= $(PROJECT_SOC)/doc
PROJECT_SOCHEX		:= $(PROJECT_SOC)/hex
PROJECT_SOCRTL		:= $(PROJECT_SOC)/rtl
PROJECT_SOCTB		:= $(PROJECT_SOC)/tb

PROJECT_SOCUTILS	:= $(PROJECT_SOC)/utils
PROJECT_SOCFILELIST	:= $(PROJECT_SOC)/filelist.f
PROJECT_SOCDEFLIST	:= $(PROJECT_SOCUTILS)/def.inc


PROJECT_SIMCOMMON   := $(PROJECT_VERIFACTION)/common
PROJECT_SIMDOC      := $(PROJECT_VERIFACTION)/doc
PROJECT_SIMPATH     := $(PROJECT_VERIFACTION)/sim
PROJECT_SIMTC       := $(PROJECT_VERIFACTION)/tc
PROJECT_SIMTH       := $(PROJECT_VERIFACTION)/th
PROJECT_SIMCFG      := $(PROJECT_VERIFACTION)/cfg
PROJECT_SIMSUBENV   := $(PROJECT_VERIFACTION)/subenv
PROJECT_SIMREG      := $(PROJECT_VERIFACTION)/reg 

PROJECT_SIMTBFILE   := $(PROJECT_SIMCFG)/tb.f
PROJECT_SIMLOG      := $(PROJECT_SIMPATH)/log
PROJECT_SIMVERDI    := $(PROJECT_SIMPATH)/verdi
PROJECT_SIMEXCE    := $(PROJECT_SIMPATH)/exce



